name: ui_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  dots_indicator: ^2.1.0
  get: 4.6.5
  google_maps_flutter: ^2.2.2
  swipe_cards: ^1.0.0


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/


